### ISSUE TITLE
cara menggunakannya gimana?

### ISSUE THREAD

**Issue by vonyrhatoe** [khalisafkari/Blogger-video-downloader#2]
sari min masih newbie

**Comment by khalisafkari** [comment]
1.Silahkan install nodejs 
2. Clone repo ini
3. Jalankan npm init -y melalui terminal/cmd dalam folder repo 
4. melalui cmd install npm i node-fetch cheerio -s
5. Jalan node js googleblogger.js

**Comment by vonyrhatoe** [comment]
ada demonya tidak mas?

**Comment by khalisafkari** [comment]
video [video](https://blogger-portcmedd.now.sh/?url=https://www.blogger.com/video.g?token=AD6v5dy6xibQ1EBFaa1lN91Il9qch9W8dAnCVk8uDihtPVLuLwc0TUdSA24IP8gRMKqxIQQgenDZQFQA2pCYwQpH3O1iOKWxVfuapwPd6QIRDVKAtunBuMnh6ALvCUkLXhCqoH4RZ6D_)

json [json](https://blogger-portcmedd.now.sh/json?url=https://www.blogger.com/video.g?token=AD6v5dy6xibQ1EBFaa1lN91Il9qch9W8dAnCVk8uDihtPVLuLwc0TUdSA24IP8gRMKqxIQQgenDZQFQA2pCYwQpH3O1iOKWxVfuapwPd6QIRDVKAtunBuMnh6ALvCUkLXhCqoH4RZ6D_)
